on:
  - push
  - pull_request

jobs:
  build-sketches:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: pa-pa-328p
          - name: jp112sdl-328p
          - name: 644p

    steps:
      # GIT Checkout
      - uses: actions/checkout@v2

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

      - name: Install Libs and Cores
        run: tests/install-deps.sh

      - name: Download sketches
        run: tests/download-sketches.sh

      - name: Compile Sketches
        run: tests/test-${{ matrix.name }}.sh
